require("plugins.blink")
require("plugins.conform")
require("plugins.dap")
require("plugins.flash")
require("plugins.git")
require("plugins.persistence")
require("plugins.mini")
require("plugins.lualine")
-- require("plugins.colorful-menu")
-- require("plugins.pretty-hover")
require("plugins.bufferline")
require("plugins.onenord")
require("plugins.grug-far")
require("plugins.markdown")
require("plugins.noice")
require("plugins.snacks")
require("plugins.treesitter")
require("plugins.whichkey")
require("plugins.yanky")
require("plugins.coding")
